# Site settings
title: "mcmah309 Blog"
description: "Tech talk and ongoing open source projects"
url: "https://yourusername.github.io" # your site's URL
baseurl: "" # subpath of your site, e.g. /blog

# Theme
theme: jekyll-theme-so-simple

# Locale
locale: "en-US"

# Reading time
read_time: true
words_per_minute: 200

# Google Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Search
search_full_content: true

# Taxonomy archive links
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer links
footer_links:
  # - title: "Twitter"
  #   url: "https://twitter.com/yourusername"
  #   icon: "fab fa-twitter-square"
  - title: "GitHub"
    url: "https://github.com/mcmah309"
    icon: "fab fa-github-square"
  # - title: "Feed"
  #   url: "/feed.xml"
  #   icon: "fas fa-rss-square"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Markdown processing
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Exclude from processing
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Front matter defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      comments: true