# Site settings
title: "Your Site Title"
description: "This is a brief description of your site. You can customize this description."
url: "https://yourusername.github.io" # your site's URL
baseurl: "" # subpath of your site, e.g. /blog

# Theme
theme: jekyll-theme-so-simple
# remote_theme: "mmistakes/so-simple-theme@3.2.0" # use this for GitHub Pages

# Site author
author:
  name: "Your Name"
  email: "your.email@example.com"
  twitter: "yourusername"
  picture: "/images/your-photo.jpg"

# Site logo
logo: "/images/site-logo.png"

# Locale
locale: "en-US"

# Reading time
read_time: true
words_per_minute: 200

# Comments via Disqus (optional)
# disqus:
#   shortname: "your-disqus-shortname"

# Google Analytics (optional)
# google_analytics: "UA-NNNNNNNN-N"

# Google Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Skin (theme color scheme)
skin: "/assets/css/skins/default.css"
# Options: "/assets/css/skins/default.css", "/assets/css/skins/light.css", "/assets/css/skins/dark.css"

# Search
search_full_content: true

# Taxonomy archive links
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer links
footer_links:
  - title: "Twitter"
    url: "https://twitter.com/yourusername"
    icon: "fab fa-twitter-square"
  - title: "GitHub"
    url: "https://github.com/yourusername"
    icon: "fab fa-github-square"
  - title: "Feed"
    url: "/feed.xml"
    icon: "fas fa-rss-square"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Markdown processing
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Exclude from processing
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Front matter defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      comments: true